DROP SCHEMA IF EXISTS `goal` ;
CREATE SCHEMA IF NOT EXISTS `goal` DEFAULT CHARACTER SET utf8 ;

CREATE USER 'goal'@'localhost' IDENTIFIED BY 'goal';
GRANT ALL PRIVILEGES ON goal.* TO 'goal'@'localhost' WITH GRANT OPTION;
